score=[]
a=str(input('name'))
a1=int(input('score'))
a2=int(input('age'))
b=str(input('name'))
b1=int(input('score'))
b2=int(input('age'))
c=str(input('name'))
c1=int(input('score'))
c2=int(input('age'))
d=str(input('name'))
d1=int(input('score'))
d2=int(input('age'))
e=str(input('name'))
e1=int(input('score'))
e2=int(input('age'))
score=[['a',a1,a2],['b',b1,b2],['c',c1,c2],['d',d1,d2],['e',e1,e2]]
print(score)

