score=list()
com_score=list()
num=int(input('人數'))
for i in range(num):
    n=(input('name'))
    s=int(input('score'))
    a=int(input('age'))
    name=list()
    name.append(n)
    name.append(s)
    name.append(a)
    score.append(name)
    com_score.append(s)
max_num=com_score.index(max(com_score))
min_num=com_score.index(min(com_score))
print('最高',max(com_score),'是',score[max_num][0])
print('最低',min(com_score),'是',score[min_num][0])
print(score)

